//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class compukter
    {
        public string id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public decimal price { get; set; }
        public Nullable<bool> instock { get; set; }
        public byte[] photo { get; set; }
        public string id_processor { get; set; }
        public string id_mother { get; set; }
        public string id_videoadapter { get; set; }
        public string id_power { get; set; }
        public string id_hard_drive { get; set; }
        public string id_ram { get; set; }
        public string id_corpus { get; set; }
        public string id_employee { get; set; }
        public int count { get; set; }
    
        public virtual corpus corpus { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual hard_drive hard_drive { get; set; }
        public virtual mother mother { get; set; }
        public virtual power power { get; set; }
        public virtual processor processor { get; set; }
        public virtual ram ram { get; set; }
        public virtual videoadapter videoadapter { get; set; }
    }
}
