//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopEntities : DbContext
    {
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<compukter> compukter { get; set; }
        public virtual DbSet<corpus> corpus { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<hard_drive> hard_drive { get; set; }
        public virtual DbSet<mother> mother { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<power> power { get; set; }
        public virtual DbSet<processor> processor { get; set; }
        public virtual DbSet<ram> ram { get; set; }
        public virtual DbSet<socket> socket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<videoadapter> videoadapter { get; set; }
    }
}
